autostop:
  enabled: true
  package: yandextank.plugins.Autostop
bfg:
  enabled: false
  package: yandextank.plugins.Bfg
console:
  enabled: true
  package: yandextank.plugins.Console
pandora:
  enabled: false
  package: yandextank.plugins.Pandora
rcheck:
  enabled: true
  package: yandextank.plugins.ResourceCheck
shellexec:
  enabled: true
  package: yandextank.plugins.ShellExec
telegraf:
  enabled: false
  package: yandextank.plugins.Telegraf
rcassert:
  enabled: true
  package: yandextank.plugins.RCAssert
influx:
  enabled: false
  package: yandextank.plugins.InfluxUploader
